name: Update README with GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Fetch GitHub Stats and Update README
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_STATS_TOKEN" \
               "https://github-readme-stats.vercel.app/api?username=mehmethanturut&show_icons=true&theme=radical" \
               -o stats.svg
          echo "![GitHub Stats](stats.svg)" > README.md

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with GitHub Stats"
          git push
